/**
 * MON GLOBAL wordmark — MONC's block lockup applied to MONG.
 *
 * Lowercase "mon" reversed out of a navy block, terminal letter in flat gold,
 * tagline beneath. Generated by `scripts/build-logo-block.py` from real
 * Montserrat outlines, so it is self-contained paths with no font dependency.
 *
 * To adjust it (block padding, tracking, tagline measure), edit the TUNING
 * block in that script and re-run. Do not hand-edit the SVGs.
 *
 * NOTE: the earlier serif treatment (`mon-global.svg`, MON + split ring, built
 * by `build-logo.py`) is still generated and still used by ../social. Both
 * scripts are live; this component renders the block version.
 */

/** Natural aspect ratio of the COMPACT block cut (viewBox 3202 x 941).
 *  Keep in step with build-logo-block.py — if the viewBox changes there, the
 *  width/height attributes here go wrong and the header reserves the wrong
 *  space on first paint. The rendered size is safe either way (width is auto,
 *  so the SVG's own viewBox governs), but the layout-shift hint is not. */
const ASPECT = 2296 / 939;

type Tone = "onDark" | "onLight";

export function Logo({
  tone = "onDark",
  className = "",
  size = 1,
}: {
  tone?: Tone;
  className?: string;
  /** Scale multiplier. 1 renders the wordmark at 50px tall. */
  size?: number;
}) {
  const height = size * 50;
  // The mark is now stacked — "mon" with GLOBAL beneath it — so the descriptor
  // has replaced the tagline and the compact and full cuts are the same
  // drawing. The -compact names are kept so nothing else has to change.
  //
  // onDark: transparent cut, so the mark sits on the page's own ground.
  // onLight: the dedicated light cut. This used to fall back to the
  // black-baked version because no light variant existed; one does now, with
  // the word in navy and GLOBAL in gold-deep (plain gold is 2.30:1 on paper).
  const src =
    tone === "onDark"
      ? "/brand/mong-block-compact-transparent.svg"
      : "/brand/mong-block-light.svg";

  // A static local SVG: next/image would need dangerouslyAllowSVG and gains
  // nothing, since there is no rasterising or resizing to do.
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src}
      alt="MON Global"
      width={Math.round(height * ASPECT)}
      height={Math.round(height)}
      className={className}
      style={{ height: `${height}px`, width: "auto" }}
    />
  );
}
